//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probadesyat
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ед изм.
    /// </summary>
    // *** Start programmer edit section *** (ЕдИзм CustomAttributes)

    // *** End programmer edit section *** (ЕдИзм CustomAttributes)
    public enum ЕдИзм
    {
        
        // *** Start programmer edit section *** (ЕдИзм.Шт CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.Шт CustomAttributes)
        Шт,
        
        // *** Start programmer edit section *** (ЕдИзм.Тонн CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.Тонн CustomAttributes)
        Тонн,
        
        // *** Start programmer edit section *** (ЕдИзм.Кг CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.Кг CustomAttributes)
        Кг,
        
        // *** Start programmer edit section *** (ЕдИзм.Л CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.Л CustomAttributes)
        Л,
    }
}
