//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probadesyat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пункт погрузки.
    /// </summary>
    // *** Start programmer edit section *** (ПунктПогрузки CustomAttributes)

    // *** End programmer edit section *** (ПунктПогрузки CustomAttributes)
    [AutoAltered()]
    [Caption("Пункт погрузки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПунктПогрузкиE", new string[] {
            "Адрес as \'Адрес\'",
            "НаимПунктаПог as \'Наим пункта пог\'"})]
    [View("ПунктПогрузкиL", new string[] {
            "Адрес as \'Адрес\'",
            "НаимПунктаПог as \'Наим пункта пог\'"})]
    public class ПунктПогрузки : ICSSoft.STORMNET.DataObject
    {
        
        private string fАдрес;
        
        private string fНаимПунктаПог;
        
        // *** Start programmer edit section *** (ПунктПогрузки CustomMembers)

        // *** End programmer edit section *** (ПунктПогрузки CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (ПунктПогрузки.Адрес CustomAttributes)

        // *** End programmer edit section *** (ПунктПогрузки.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (ПунктПогрузки.Адрес Get start)

                // *** End programmer edit section *** (ПунктПогрузки.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (ПунктПогрузки.Адрес Get end)

                // *** End programmer edit section *** (ПунктПогрузки.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПунктПогрузки.Адрес Set start)

                // *** End programmer edit section *** (ПунктПогрузки.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (ПунктПогрузки.Адрес Set end)

                // *** End programmer edit section *** (ПунктПогрузки.Адрес Set end)
            }
        }
        
        /// <summary>
        /// НаимПунктаПог.
        /// </summary>
        // *** Start programmer edit section *** (ПунктПогрузки.НаимПунктаПог CustomAttributes)

        // *** End programmer edit section *** (ПунктПогрузки.НаимПунктаПог CustomAttributes)
        [StrLen(255)]
        public virtual string НаимПунктаПог
        {
            get
            {
                // *** Start programmer edit section *** (ПунктПогрузки.НаимПунктаПог Get start)

                // *** End programmer edit section *** (ПунктПогрузки.НаимПунктаПог Get start)
                string result = this.fНаимПунктаПог;
                // *** Start programmer edit section *** (ПунктПогрузки.НаимПунктаПог Get end)

                // *** End programmer edit section *** (ПунктПогрузки.НаимПунктаПог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПунктПогрузки.НаимПунктаПог Set start)

                // *** End programmer edit section *** (ПунктПогрузки.НаимПунктаПог Set start)
                this.fНаимПунктаПог = value;
                // *** Start programmer edit section *** (ПунктПогрузки.НаимПунктаПог Set end)

                // *** End programmer edit section *** (ПунктПогрузки.НаимПунктаПог Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПунктПогрузкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПунктПогрузкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПунктПогрузкиE", typeof(IIS.Probadesyat.ПунктПогрузки));
                }
            }
            
            /// <summary>
            /// "ПунктПогрузкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПунктПогрузкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПунктПогрузкиL", typeof(IIS.Probadesyat.ПунктПогрузки));
                }
            }
        }
    }
}
