//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probadesyat
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Удовл кл.
    /// </summary>
    // *** Start programmer edit section *** (УдовлКл CustomAttributes)

    // *** End programmer edit section *** (УдовлКл CustomAttributes)
    public enum УдовлКл
    {
        
        // *** Start programmer edit section *** (УдовлКл.Удовлетворен CustomAttributes)

        // *** End programmer edit section *** (УдовлКл.Удовлетворен CustomAttributes)
        Удовлетворен,
        
        // *** Start programmer edit section *** (УдовлКл.НеУдовлетворен CustomAttributes)

        // *** End programmer edit section *** (УдовлКл.НеУдовлетворен CustomAttributes)
        НеУдовлетворен,
    }
}
