//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probadesyat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Формир распр.
    /// </summary>
    // *** Start programmer edit section *** (ФормирРаспр CustomAttributes)

    // *** End programmer edit section *** (ФормирРаспр CustomAttributes)
    [AutoAltered()]
    [Caption("Формирование распределений")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормирРаспрE", new string[] {
            "Дата as \'Дата\'",
            "НомерДокРаспр as \'Номер документа распределения\'",
            "СписокБарж as \'Номер баржи\'",
            "ПунктПогрузки as \'Адрес пункта погрузки\'",
            "СписокКонтей as \'Номер контейнера\'",
            "ДокумПоставки as \'Номер документа поставки\'",
            "ДокумПоставки.Клиенты.НаимЗаказчика as \'Заказчик\'",
            "ДокумПоставки.Клиенты.Телефон as \'Телефон\'",
            "ДокумПоставки.Клиенты.АдресПоставки as \'Адрес поставки\'"})]
    [MasterViewDefineAttribute("ФормирРаспрE", "СписокБарж", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерБаржи")]
    [MasterViewDefineAttribute("ФормирРаспрE", "ПунктПогрузки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [MasterViewDefineAttribute("ФормирРаспрE", "СписокКонтей", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерКонтей")]
    [MasterViewDefineAttribute("ФормирРаспрE", "ДокумПоставки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерДогов")]
    [View("ФормирРаспрL", new string[] {
            "Дата as \'Дата\'",
            "НомерДокРаспр as \'Номер документа распределения\'",
            "СписокБарж.НомерБаржи as \'Номер баржи\'",
            "ДокумПоставки.НомерДогов as \'Номер документа поставки\'",
            "ПунктПогрузки.Адрес as \'Адрес пункта погрузки\'",
            "СписокКонтей.НомерКонтей as \'Номер контейнера\'"})]
    public class ФормирРаспр : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fНомерДокРаспр;
        
        private IIS.Probadesyat.ПунктПогрузки fПунктПогрузки;
        
        private IIS.Probadesyat.СписокБарж fСписокБарж;
        
        private IIS.Probadesyat.ДокумПоставки fДокумПоставки;
        
        private IIS.Probadesyat.СписокКонтей fСписокКонтей;
        
        // *** Start programmer edit section *** (ФормирРаспр CustomMembers)

        // *** End programmer edit section *** (ФормирРаспр CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.Дата CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.Дата Get start)

                // *** End programmer edit section *** (ФормирРаспр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ФормирРаспр.Дата Get end)

                // *** End programmer edit section *** (ФормирРаспр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.Дата Set start)

                // *** End programmer edit section *** (ФормирРаспр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ФормирРаспр.Дата Set end)

                // *** End programmer edit section *** (ФормирРаспр.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерДокРаспр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.НомерДокРаспр CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.НомерДокРаспр CustomAttributes)
        public virtual int НомерДокРаспр
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.НомерДокРаспр Get start)

                // *** End programmer edit section *** (ФормирРаспр.НомерДокРаспр Get start)
                int result = this.fНомерДокРаспр;
                // *** Start programmer edit section *** (ФормирРаспр.НомерДокРаспр Get end)

                // *** End programmer edit section *** (ФормирРаспр.НомерДокРаспр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.НомерДокРаспр Set start)

                // *** End programmer edit section *** (ФормирРаспр.НомерДокРаспр Set start)
                this.fНомерДокРаспр = value;
                // *** Start programmer edit section *** (ФормирРаспр.НомерДокРаспр Set end)

                // *** End programmer edit section *** (ФормирРаспр.НомерДокРаспр Set end)
            }
        }
        
        /// <summary>
        /// Формир распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.ДокумПоставки CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.ДокумПоставки CustomAttributes)
        [PropertyStorage(new string[] {
                "ДокумПоставки"})]
        [NotNull()]
        public virtual IIS.Probadesyat.ДокумПоставки ДокумПоставки
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.ДокумПоставки Get start)

                // *** End programmer edit section *** (ФормирРаспр.ДокумПоставки Get start)
                IIS.Probadesyat.ДокумПоставки result = this.fДокумПоставки;
                // *** Start programmer edit section *** (ФормирРаспр.ДокумПоставки Get end)

                // *** End programmer edit section *** (ФормирРаспр.ДокумПоставки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.ДокумПоставки Set start)

                // *** End programmer edit section *** (ФормирРаспр.ДокумПоставки Set start)
                this.fДокумПоставки = value;
                // *** Start programmer edit section *** (ФормирРаспр.ДокумПоставки Set end)

                // *** End programmer edit section *** (ФормирРаспр.ДокумПоставки Set end)
            }
        }
        
        /// <summary>
        /// Формир распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.ПунктПогрузки CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.ПунктПогрузки CustomAttributes)
        [PropertyStorage(new string[] {
                "ПунктПогрузки"})]
        [NotNull()]
        public virtual IIS.Probadesyat.ПунктПогрузки ПунктПогрузки
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.ПунктПогрузки Get start)

                // *** End programmer edit section *** (ФормирРаспр.ПунктПогрузки Get start)
                IIS.Probadesyat.ПунктПогрузки result = this.fПунктПогрузки;
                // *** Start programmer edit section *** (ФормирРаспр.ПунктПогрузки Get end)

                // *** End programmer edit section *** (ФормирРаспр.ПунктПогрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.ПунктПогрузки Set start)

                // *** End programmer edit section *** (ФормирРаспр.ПунктПогрузки Set start)
                this.fПунктПогрузки = value;
                // *** Start programmer edit section *** (ФормирРаспр.ПунктПогрузки Set end)

                // *** End programmer edit section *** (ФормирРаспр.ПунктПогрузки Set end)
            }
        }
        
        /// <summary>
        /// Формир распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.СписокБарж CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.СписокБарж CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокБарж"})]
        [NotNull()]
        public virtual IIS.Probadesyat.СписокБарж СписокБарж
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.СписокБарж Get start)

                // *** End programmer edit section *** (ФормирРаспр.СписокБарж Get start)
                IIS.Probadesyat.СписокБарж result = this.fСписокБарж;
                // *** Start programmer edit section *** (ФормирРаспр.СписокБарж Get end)

                // *** End programmer edit section *** (ФормирРаспр.СписокБарж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.СписокБарж Set start)

                // *** End programmer edit section *** (ФормирРаспр.СписокБарж Set start)
                this.fСписокБарж = value;
                // *** Start programmer edit section *** (ФормирРаспр.СписокБарж Set end)

                // *** End programmer edit section *** (ФормирРаспр.СписокБарж Set end)
            }
        }
        
        /// <summary>
        /// Формир распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.СписокКонтей CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.СписокКонтей CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокКонтей"})]
        [NotNull()]
        public virtual IIS.Probadesyat.СписокКонтей СписокКонтей
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.СписокКонтей Get start)

                // *** End programmer edit section *** (ФормирРаспр.СписокКонтей Get start)
                IIS.Probadesyat.СписокКонтей result = this.fСписокКонтей;
                // *** Start programmer edit section *** (ФормирРаспр.СписокКонтей Get end)

                // *** End programmer edit section *** (ФормирРаспр.СписокКонтей Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.СписокКонтей Set start)

                // *** End programmer edit section *** (ФормирРаспр.СписокКонтей Set start)
                this.fСписокКонтей = value;
                // *** Start programmer edit section *** (ФормирРаспр.СписокКонтей Set end)

                // *** End programmer edit section *** (ФормирРаспр.СписокКонтей Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормирРаспрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирРаспрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирРаспрE", typeof(IIS.Probadesyat.ФормирРаспр));
                }
            }
            
            /// <summary>
            /// "ФормирРаспрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирРаспрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирРаспрL", typeof(IIS.Probadesyat.ФормирРаспр));
                }
            }
        }
    }
}
